## pip 安装软件报错 SSL: CERTIFICATE_VERIFY_FAILED

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

【原因】：pyhon升级到2.7.9以后，引入了一个新特性，当使用urllib打开https的链接时，会检验一次ssl证书。而当目标网站使用的是自签名证书时，就会抛出urllib2.URLError的错误。


【解决】：
## 1. 安装时指定信任主机
```sh
# -- trusted-host
pip install --upgrade pandas --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host mirrors.aliyun.com
```

## 2. pip.conf Windows 下位 pip.ini 中添加 install 配置项

```conf
[install]
trusted-host=pypi.org,pypi.python.org,files.pythonhosted.org,pypi.tuna.tsinghua.edu.cn,mirrors.aliyun.com
```

## 3. File "D:\Python38\lib\asyncio\events.py", line 501, in add_reader raise NotImplementedError 报错解决

【解决】：找到 tornado/platform/asyncio.py 文件修改，添加代码如下：（参见：[File "\asyncio\events.py", line 501, in add_reader raise NotImplementedError 报错解决](https://blog.csdn.net/agent_bin/article/details/103082046)）

```python
import sys

if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```